included:
  - Issue-tracker
excluded:
  - Pods
  - Issue-tracker/IssueListCollectionViewController.swift
disabled_rules:
  - todo
  - trailing_whitespace
  - function_body_length
  - line_length
indentation_width:
  indentation_width: 4
force_unwrapping:
  severity: error
type_body_length:
  - 200 # warning
  - 400 # error
opt_in_rules:
  - force_unwrapping
  - indentation_width
  - sorted_imports
  - multiline_arguments
  - multiline_parameters_brackets
