name: FE CI

on:
  push:
    branches: [ "release" ]

env:
  S3_BUCKET_NAME: 2023-issue-tracker-fe
  CODE_DEPLOY_APPLICATION_NAME: issue-tracker-fe-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: issue-tracker-fe-codedeploy-app-group
  working-directory: ./fe # 이 코드는 제 프로젝트 경로를 맞춰주기 위해 적어주었습니다. 필요하시면 적으세요 !
  REACT_APP_PROD_API_URL: ${{ secrets.REACT_APP_PROD_API_URL }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest


    steps:
      # 1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2) 담당자 체크
      - name: Check if specific user pushed
        run: |
          if [ "${{ github.actor }}" == "poco111" ] || [ "${{ github.actor }}" == "saseungg" ]; then
            echo "The specific user pushed. Perform the necessary actions here."
          fi

      # 3) node 셋팅
      - name: Set node@v1
        uses: actions/setup-node@v3

      - name: check Node v
        run: node -v

      - name: Install npm
        run: sudo apt install npm

      - name: check npm
        run: npm -v

      - name: install dependency
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Generate build
        run: npm run build
        working-directory: ${{ env.working-directory }}

      # AWS 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}

      # 필요한 파일 3개 압축
      - name: Zip files
        run: |
          zip -r upload.zip ./fe/build ./scripts/*.sh ./appspec.yml

      # AWS S3에 업로드
      - name: Upload to AWS S3
        run: |
          aws s3 cp upload.zip s3://${S3_BUCKET_NAME}/upload.zip

      # AWS EC2에 Deploy
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=upload.zip,bundleType=zip